
# version: '2'

# #mis dockerfile
# services:
#   #frontreact
#   client:
#     container_name: docker-front
#     build: ./frontreact
#     ports:
#       - 8080:3000
#   #back
#   server:
#     container_name: docker-back
#     build: ./back
#     ports:
#       - 8081:4000

#docker-compose yml

version: '2'

services:
  #frontreact
  client:
    container_name: docker-front
    build: ./frontreact
    ports:
      - 8080:3000
  server:
     container_name: docker-back
     build: ./back
     ports:
       - 8081:4000
  db:
    container_name: postgres-image
    build: ./back/database
    ports:
      - "5432"
    volumes:
      - ./back/db/scriptProyecto.sql:/docker-entrypoint.initdb.d/db.sql
    environment:
      POSTGRES_DB: easyTaxiDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
